package com.agrilink.rwanda.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProduceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduceAllPropertiesEquals(Produce expected, Produce actual) {
        assertProduceAutoGeneratedPropertiesEquals(expected, actual);
        assertProduceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduceAllUpdatablePropertiesEquals(Produce expected, Produce actual) {
        assertProduceUpdatableFieldsEquals(expected, actual);
        assertProduceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduceAutoGeneratedPropertiesEquals(Produce expected, Produce actual) {
        assertThat(actual)
            .as("Verify Produce auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduceUpdatableFieldsEquals(Produce expected, Produce actual) {
        assertThat(actual)
            .as("Verify Produce relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProduceUpdatableRelationshipsEquals(Produce expected, Produce actual) {
        assertThat(actual)
            .as("Verify Produce relationships")
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
